const { faker } = require("@faker-js/faker");

module.exports = {
  up: async (queryInterface, Sequelize) => {
    const languages = [
      { id: 1, name: "English" },
      { id: 2, name: "Français" },
      { id: 3, name: "Español" },
    ];

    // English Lessons
    const englishLessons = [
      {
        title: "English - Level 1",
        type: "multiple",
        question: "What is the translation of 'Bonjour'?",
        options: ["Hello", "Goodbye", "Please", "Thank you"],
        answer: "Hello",
        points: 200,
        languageId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "English - Level 2",
        type: "order",
        question: "Rearrange the sentence: 'I to going am school'",
        scrambledSentence: ["I", "to", "going", "am", "school"],
        correctOrder: ["I", "am", "going", "to", "school"],
        points: 150,
        languageId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "English - Level 3",
        type: "true_false",
        question: "Is Paris the capital of the United Kingdom?",
        isTrue: false,
        points: 100,
        languageId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "English - Level 4",
        type: "multiple",
        question: "What is the translation of 'Merci'?",
        options: ["Thank you", "Please", "You're welcome", "Goodbye"],
        answer: "Thank you",
        points: 200,
        languageId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "English - Level 5",
        type: "order",
        question: "Rearrange the sentence: 'She book a reading is'",
        scrambledSentence: ["She", "book", "a", "reading", "is"],
        correctOrder: ["She", "is", "reading", "a", "book"],
        points: 150,
        languageId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "English - Level 6",
        type: "true_false",
        question: "The Statue of Liberty is in New York City.",
        isTrue: true,
        points: 100,
        languageId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "English - Level 7",
        type: "multiple",
        question: "What is the translation of 'Au revoir'?",
        options: ["Goodbye", "Hello", "Please", "Thank you"],
        answer: "Goodbye",
        points: 150,
        languageId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "English - Level 8",
        type: "order",
        question: "Rearrange the sentence: 'They to cinema the going are'",
        scrambledSentence: ["They", "to", "cinema", "the", "going", "are"],
        correctOrder: ["They", "are", "going", "to", "the", "cinema"],
        points: 200,
        languageId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "English - Level 9",
        type: "true_false",
        question: "Mount Everest is the highest mountain in the world.",
        isTrue: true,
        points: 100,
        languageId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "English - Level 10",
        type: "multiple",
        question: "What is the translation of 'S'il vous plaît'?",
        options: ["Please", "Thank you", "Goodbye", "Hello"],
        answer: "Please",
        points: 150,
        languageId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "English - Level 11",
        type: "order",
        question: "Rearrange the sentence: 'He bike a riding is'",
        scrambledSentence: ["He", "bike", "a", "riding", "is"],
        correctOrder: ["He", "is", "riding", "a", "bike"],
        points: 200,
        languageId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "English - Level 12",
        type: "true_false",
        question: "The Amazon River is the longest river in the world.",
        isTrue: false,
        points: 100,
        languageId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "English - Level 13",
        type: "multiple",
        question: "What is the translation of 'Bonne nuit'?",
        options: ["Good night", "Good morning", "Goodbye", "Thank you"],
        answer: "Good night",
        points: 150,
        languageId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ];

    // French Lessons
    const frenchLessons = [
      {
        title: "Français - Niveau 4",
        type: "multiple",
        question: "Comment dit-on 'Goodbye' en français ?",
        options: ["Au revoir", "Merci", "Bonjour", "S'il vous plaît"],
        answer: "Au revoir",
        points: 150,
        languageId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Français - Niveau 5",
        type: "order",
        question: "Réorganisez la phrase : 'chat noir un est'",
        scrambledSentence: ["chat", "noir", "un", "est"],
        correctOrder: ["un", "chat", "noir", "est"],
        points: 200,
        languageId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Français - Niveau 6",
        type: "true_false",
        question: "Le Louvre est un musée à Paris.",
        isTrue: true,
        points: 100,
        languageId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Français - Niveau 7",
        type: "multiple",
        question: "Quelle est la traduction de 'Please' en français ?",
        options: ["S'il vous plaît", "Merci", "Au revoir", "Bonjour"],
        answer: "S'il vous plaît",
        points: 150,
        languageId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Français - Niveau 8",
        type: "order",
        question: "Réorganisez la phrase : 'je café boire veux un'",
        scrambledSentence: ["je", "café", "boire", "veux", "un"],
        correctOrder: ["je", "veux", "boire", "un", "café"],
        points: 250,
        languageId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Français - Niveau 9",
        type: "true_false",
        question: "La Seine est un fleuve qui traverse Paris.",
        isTrue: true,
        points: 100,
        languageId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Français - Niveau 10",
        type: "multiple",
        question: "Quelle est la traduction de 'Yes' en français ?",
        options: ["Oui", "Non", "Peut-être", "Jamais"],
        answer: "Oui",
        points: 100,
        languageId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Français - Niveau 11",
        type: "order",
        question: "Réorganisez la phrase : 'elle chanson une chante'",
        scrambledSentence: ["elle", "chanson", "une", "chante"],
        correctOrder: ["elle", "chante", "une", "chanson"],
        points: 200,
        languageId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Français - Niveau 12",
        type: "true_false",
        question: "Le Mont Saint-Michel est situé en Normandie.",
        isTrue: true,
        points: 100,
        languageId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Français - Niveau 13",
        type: "multiple",
        question: "Comment dit-on 'Thank you very much' en français ?",
        options: [
          "Merci beaucoup",
          "Merci bien",
          "Je vous en prie",
          "Au revoir",
        ],
        answer: "Merci beaucoup",
        points: 150,
        languageId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ];

    // Spanish Lessons
    const spanishLessons = [
      {
        title: "Español - Nivel 1",
        type: "multiple",
        question: "¿Cuál es la traducción de 'Thank you'?",
        options: ["Gracias", "Hola", "Por favor", "Adiós"],
        answer: "Gracias",
        points: 200,
        languageId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Español - Nivel 2",
        type: "order",
        question: "Reorganiza la frase: 'yo tienda la a voy'",
        scrambledSentence: ["yo", "tienda", "la", "a", "voy"],
        correctOrder: ["yo", "voy", "a", "la", "tienda"],
        points: 150,
        languageId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Español - Nivel 3",
        type: "true_false",
        question: "La Sagrada Familia está en Madrid.",
        isTrue: false,
        points: 100,
        languageId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Español - Nivel 4",
        type: "multiple",
        question: "¿Cuál es la traducción de 'Hello'?",
        options: ["Hola", "Adiós", "Gracias", "Por favor"],
        answer: "Hola",
        points: 200,
        languageId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Español - Nivel 5",
        type: "order",
        question: "Reorganiza la frase: 'el parque voy al'",
        scrambledSentence: ["el", "parque", "voy", "al"],
        correctOrder: ["voy", "al", "parque"],
        points: 150,
        languageId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Español - Nivel 6",
        type: "true_false",
        question: "El flamenco es un baile tradicional de España.",
        isTrue: true,
        points: 100,
        languageId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Español - Nivel 7",
        type: "multiple",
        question: "¿Cuál es la traducción de 'Goodbye'?",
        options: ["Adiós", "Hola", "Por favor", "Gracias"],
        answer: "Adiós",
        points: 150,
        languageId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Español - Nivel 8",
        type: "order",
        question: "Reorganiza la frase: 'una leer libro quiero'",
        scrambledSentence: ["una", "leer", "libro", "quiero"],
        correctOrder: ["quiero", "leer", "un", "libro"],
        points: 200,
        languageId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Español - Nivel 9",
        type: "true_false",
        question: "El Amazonas es el río más largo de España.",
        isTrue: false,
        points: 100,
        languageId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Español - Nivel 10",
        type: "multiple",
        question: "¿Cuál es la traducción de 'Please'?",
        options: ["Por favor", "Gracias", "Hola", "Adiós"],
        answer: "Por favor",
        points: 150,
        languageId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Español - Nivel 11",
        type: "order",
        question: "Reorganiza la frase: 'él televisión mira la'",
        scrambledSentence: ["él", "televisión", "mira", "la"],
        correctOrder: ["él", "mira", "la", "televisión"],
        points: 200,
        languageId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Español - Nivel 12",
        type: "true_false",
        question: "La Alhambra está en Andalucía.",
        isTrue: true,
        points: 100,
        languageId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Español - Nivel 13",
        type: "multiple",
        question: "¿Cuál es la traducción de 'Good night'?",
        options: ["Buenas noches", "Buenos días", "Adiós", "Gracias"],
        answer: "Buenas noches",
        points: 150,
        languageId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ];

    // Combine lessons into a single array
    const lessons = [...englishLessons, ...frenchLessons, ...spanishLessons];

    return queryInterface.bulkCreate(lessons);
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.truncate();
  },
};
